www.worldisawesome.fun/Models/DBContext/Experiences.cs
using System;
using System.Collections.Generic;
using www.worldisawesome.fun.Models;

namespace www.worldisawesome.fun.DataModels
{
    public partial class Experiences
    {
        public Experiences()
        {
            UsersToDo = new HashSet<Users_ExperiencesToDo>();
        }

        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public DateTime? Date { get; set; }
        public TimeSpan? Time { get; set; }
        public MorningNightEnum? MorningNightEnum { get; set; }
        public Guid? MediaFileId { get; set; }
        public Guid? PlaceId { get; set; }
        public Guid UserId { get; set; }
        public DateTimeOffset DateTimeCreated { get; set; }
        public PrivacyLevelEnum? PrivacyLevel { get; set; }
        public ExperienceStatusEnum StatusEnum { get; set; }

        public virtual Files MediaFile { get; set; }
        public virtual Places Place { get; set; }
        public virtual Users User { get; set; }

        public virtual ICollection<Users_ExperiencesToDo> UsersToDo { get; set; }
    }
}

www.worldisawesome.fun/Models/DBContext/Places.cs
using System;
using System.Collections.Generic;

namespace www.worldisawesome.fun.DataModels
{
    public partial class Places
    {
        public Places()
        {
            Experiences = new HashSet<Experiences>();
            Users = new HashSet<Users>();
        }

        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
        public Guid? ProfilePictureFileId { get; set; }

        public virtual Files ProfilePictureFile { get; set; }
        public virtual ICollection<Experiences> Experiences { get; set; }
        public virtual ICollection<Users> Users { get; set; }
    }
}

www.worldisawesome.fun/Models/View/Experience.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Http;
using www.worldisawesome.fun.Models;

namespace www.worldisawesome.fun.ViewModels
{
    public class Experience
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public MorningNightEnum? MorningNightEnum { get; set; }
        public double DateTimeCreated { get; set; }
        public PrivacyLevelEnum? PrivacyLevel { get; set; }
        public string FileId { get; set; }
        public string FileName { get; set; }
        public string FileType { get; set; }
        public IFormFile File { get; set; }

        // public Place Place { get; set; }
        public string PlaceId { get; set; }
        public string PlaceName { get; set; }
        public string PlaceDescription { get; set; }
        public decimal PlaceLatitude { get; set; }
        public decimal PlaceLongitude { get; set; }
        public string UserId { get; set; }
        public string UserNickname { get; set; }
        public string UserName { get; set; }
        public string UserSurname { get; set; }
        public string UserProfilePhotoFileId { get; set; }
        public List<User> UsersToDoList { get; set; }
        public ExperienceStatusEnum StatusEnum { get; set; }
        public bool? IsMine { get; set; }
        public bool? IsToDo { get; set; }
    }
}

www.worldisawesome.fun/Models/View/Place.cs
namespace www.worldisawesome.fun.ViewModels
{
    public partial class Place
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
        public string PictureId { get; set; }
        public bool? IsMine { get; set; }
    }
}

www.worldisawesome.fun/Controllers/ViewController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using www.worldisawesome.fun.DBContext;
using www.worldisawesome.fun.ExceptionModels;
using www.worldisawesome.fun.Models;
using www.worldisawesome.fun.Services;

namespace www.worldisawesome.fun.Controllers
{
    [Route("{controller=Home}/{action=Index}/{id?}")]
    public class ViewController : Controller
    {
        private readonly WorldIsAwesomeContext _dbContext;
        private readonly IConfiguration _configuration;

        private readonly string Folder_ExperiencesMedia;
        private readonly string Folder_UsersPictures;
        private readonly string Folder_PlacesPictures;

        bool isUserLogged = false;
        Guid? userLoggedIdGuid = null;


        public ViewController(
            WorldIsAwesomeContext dbContext,
            IConfiguration configuration
        )
        {
            _dbContext = dbContext;
            _configuration = configuration;

            Folder_ExperiencesMedia = _configuration.GetValue<string>("FolderManagement:ExperiencesMedia");
            Folder_UsersPictures = _configuration.GetValue<string>("FolderManagement:UsersPictures");
            Folder_PlacesPictures = _configuration.GetValue<string>("FolderManagement:PlacesPictures");
        }

        private async Task SetSessionParams()
        {
            var userLoggedId = HttpContext.User.Claims.FirstOrDefault(x => x.Type == ClaimTypes.NameIdentifier)?.Value;

            if (userLoggedId != null && userLoggedId != default)
            {
                var userLogged = await _dbContext.Users
                    .Where(x => x.Id == Guid.Parse(userLoggedId) && x.StatusEnum == Models.UserStatusEnum.Activated)
                    .Include(x => x.ResidencePlace)
                    .FirstOrDefaultAsync();

                if (userLogged == null)
                {
                    isUserLogged = false;
                    userLoggedIdGuid = null;
                    ViewBag.UserLogged = null;
                    await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

                    //throw new MyUnauthorizedException("User set is wrong or not active");
                }
                else
                {
                    userLogged.LastAccess = DateTimeOffset.Now;
                    _dbContext.Users.Update(userLogged);
                    await _dbContext.SaveChangesAsync();

                    isUserLogged = true;
                    userLoggedIdGuid = userLogged.Id;
                    ViewBag.UserLogged = new ViewModels.User()
                    {
                        Id = userLogged.Id.ToString(),
                        Nickname = userLogged.Nickname,
                        Name = userLogged.Name,
                        Surname = userLogged.Surname,
                        Description = userLogged.Description,
                        BirthDate = DateTimeHelpers.GetDateFormattedFromDateTime(userLogged.BirthDate),
                        ProfilePhotoFileId = userLogged.ProfilePhotoFileId.ToString(),
                        Mail = userLogged.Mail,
                        LastAccess = DateTimeHelpers.GetMillisecondsFromDateTimeOffset(userLogged.LastAccess),
                        ResidencePlaceId = userLogged.ResidencePlace?.Id.ToString(),
                        ResidencePlaceName = userLogged.ResidencePlace?.Name
                    };
                }
            }

            ViewBag.IsUserLogged = isUserLogged;
            ViewBag.UserLoggedIdGuid = userLoggedIdGuid;
        }


        #region pages
        public async Task<IActionResult> Experience(Guid experienceId)
        {
            try
            {
                await SetSessionParams();

                ViewBag.HeaderTitle = "Experience";
                ViewBag.Experience = await _dbContext.Experiences
                    .Where(x => x.Id == experienceId &&
                        ((isUserLogged && x.UserId == userLoggedIdGuid) || x.StatusEnum == Models.ExperienceStatusEnum.Completed) && 
                        ((isUserLogged && x.UserId == userLoggedIdGuid) || (isUserLogged && x.PrivacyLevel == PrivacyLevelEnum.Confidential && _dbContext.Users_UsersFriends.Any(uf => ((uf.UserId == userLoggedIdGuid && uf.UserFriendId == x.UserId) || (uf.UserId == x.UserId && uf.UserFriendId == userLoggedIdGuid)) && uf.StatusEnum == UserFriendStatusEnum.Accepted)) || x.PrivacyLevel == PrivacyLevelEnum.Public))
                    .Include(x => x.User)
                    .Include(x => x.Place)
                    .Include(x => x.UsersToDo)
                    .Include(x => x.MediaFile)
                    .Select(x => new ViewModels.Experience()
                    {
                        Id = x.Id.ToString(),
                        Name = x.Name,
                        Description = x.Description,
                        Date = DateTimeHelpers.GetDateFormattedFromDateTime(x.Date),
                        Time = DateTimeHelpers.GetTimeFormattedFromTimeSpan(x.Time.Value),
                        PrivacyLevel = x.PrivacyLevel,
                        MorningNightEnum = x.MorningNightEnum,
                        StatusEnum = x.StatusEnum,
                        FileId = x.MediaFile.Id.ToString(),
                        FileName = x.MediaFile.FileName,
                        FileType = x.MediaFile.FileType,
                        UserId = x.User.Id.ToString(),
                        UserName = x.User.Name,
                        UserSurname = x.User.Surname,
                        UserNickname = x.User.Nickname,
                        UserProfilePhotoFileId = x.User.ProfilePhotoFileId.ToString(),
                        PlaceId = x.Place.Id.ToString(),
                        PlaceName = x.Place.Name,
                        UsersToDoList = x.UsersToDo.Select(x => new ViewModels.User()
                        {
                            Id = x.User.Id.ToString(),
                            Nickname = x.User.Nickname,
                            Name = x.User.Name,
                            Surname = x.User.Surname
                        }).ToList()
                    }).FirstOrDefaultAsync();

                if (ViewBag.Experience == null) throw new MyException("Experience not found");

                ViewBag.IsMine = ViewBag.IsUserLogged && ViewBag.Experience.UserId.Equals(ViewBag.UserLogged.Id, StringComparison.OrdinalIgnoreCase);
                ViewBag.IsToDo = ViewBag.IsUserLogged && ViewBag.Experience.UsersToDoList != null && ((ViewBag.Experience.UsersToDoList as IEnumerable<ViewModels.User>).FirstOrDefault(x => x.Id.Equals(ViewBag.UserLogged.Id, StringComparison.OrdinalIgnoreCase)) != null);

                //ViewBag.FileStream = await GetMediaStream(ViewBag.Experience.FileId);

                return View();
            }
            catch (Exception e)
            {
                throw e;
            }
        }

        public async Task<IActionResult> Place(Guid placeId, Models.MorningNightEnum morningNightEnum, Models.ViewTypeEnum viewTypeEnum, System.Guid? userId)
        {
            try
            {
                await SetSessionParams();

                // var maxLength_description = 100;
                var isUserSet = userId != null && userId != Guid.Empty;
                var isMine = ViewBag.IsUserLogged && isUserSet && userId == ViewBag.UserLoggedIdGuid;

                ViewBag.HeaderTitle = "Place";

                if ((viewTypeEnum == Models.ViewTypeEnum.MyExperiences || viewTypeEnum == Models.ViewTypeEnum.ExperiencesToDo) && userId == null)
                {
                    throw new MyException("User not set");
                } else if (userId != null && viewTypeEnum == ViewTypeEnum.Default)
                {
                    viewTypeEnum = ViewTypeEnum.MyExperiences;
                    // throw new MyException("ViewType not set");
                }

                ViewBag.IsMine = isMine;
                ViewBag.IsUserSet = isUserSet;

                ViewBag.MorningNightEnum = morningNightEnum;

                ViewBag.ViewTypeEnum = viewTypeEnum;

                if (isUserSet)
                {
                    ViewBag.User = await _dbContext.Users
                            .Where(x => x.Id == userId)
                            .Select(x => new ViewModels.User()
                            {
                                Id = x.Id.ToString(),
                                Nickname = x.Nickname,
                                Name = x.Name,
                                Surname = x.Surname,
                                Description = x.Description,
                                ProfilePhotoFileId = x.ProfilePhotoFile.Id.ToString(),
                                ProfilePhotoFileName = x.ProfilePhotoFile.FileName,
                                ProfilePhotoFileType = x.ProfilePhotoFile.FileType
                            }).FirstOrDefaultAsync();
                }

                ViewBag.Place = await _dbContext
                        .View_PlaceExperiences
                        .Where(x => x.PlaceId == placeId)
                        .GroupBy(x => new { x.PlaceId, x.PlaceName, x.PlaceDescription, x.PlaceLatitude, x.PlaceLongitude, x.PlaceProfilePictureFileId })
                        .OrderBy(x => x.Key.PlaceName)
                        .Select(x => new ViewModels.Place()
                        {
                            Id = x.Key.PlaceId.ToString(),
                            Name = x.Key.PlaceName,
                            Description = x.Key.PlaceDescription,

www.worldisawesome.fun/Views/Search/Experiences.cshtml
@{
    @using www.worldisawesome.fun;

    if (ViewBag.IsUserSet)
    {
        ViewBag.PictureStream_Preview = Context.Request.Scheme + "://" + Context.Request.Host + Url.Action("GetUserPictureStream", "View", new { pictureId = ViewBag.User.ProfilePhotoFileId, isPreview = true });
    }
}

<!DOCTYPE html>
<html lang="en">

<head>
    @{await Html.RenderPartialAsync("_HeadBase"); }
    <title>Search experiences | World is Awesome .fun</title>

    <meta name="description" content="Search experiences in World is Awesome .fun, WiA" />
    <meta name="keywords"
          content="World is Awesome, World is Awesome .fun, World, Awesome, fun, wia, wia.fun, wia fun, experience, Diary, Travel, Trip, traveller, photo, video, search, experiences, photo, picture">


    <!-- external -->
    <link href="~/lib/font_nunito/Nunito.css" rel="stylesheet">

    <!-- internal -->
    <link rel="stylesheet" href="~/css/style_material.min.css">
    <link rel="stylesheet" href="~/css/style.min.css">

    <script src="~/js/script_vars.min.js" type="text/javascript"></script>
    <script src="~/js/script_apicall.min.js" type="text/javascript"></script>
    <script src="~/js/script_search_experiences.js" type="text/javascript"></script>
</head>

<body class="loading @(ViewBag.IsUserLogged ? "logged" : "") @(ViewBag.IsMine ? "ismine" : "")">
    @{await Html.RenderPartialAsync("_Base"); }


    @{await Html.RenderPartialAsync("_Header"); }


    <div class="article-container" id="experiences-search-list-popup">

        <div class="article">
            @if (ViewBag.IsUserSet)
            {
                <div class="profile-selected-container">
                    <a href="/View/User?UserId=@ViewBag.User.Id" title="Profile picture" id="userselected-button" class="profile-selected">
                        <img src="@ViewBag.PictureStream_Preview" onerror="this.src='/images/icons/user_avatar_default.svg'" class="icon" alt="profile picture" />
                        <h3 class="text">@ViewBag.User.Nickname</h3>
                    </a>
                </div>
            }

            <div class="article-header d-flex align-items">
                <img src="/images/icons/experience_search.svg" class="article-icon" alt="search experiences" />
                <h2 class="article-title flex-auto">
                    @(ViewBag.IsUserSet ? "Experiences" : "Global Experiences")
                </h2>
            </div>
            <div class="article-body">
                <div class="search-list-container">
                    <div class="input-container search-container" id="experiences-search-container">
                        <label for="experiences-search" class="label">Search</label>
                        <div class="d-flex align-items">
                            <input type="search" placeholder="Weekend in London" id="experiences-search"
                                   class="input" />

                            <div id="morningnight-button" class="small icon ml-05" title="Change daytime" onclick="changeMorningNight()"></div>
                            @if (ViewBag.IsUserSet)
                            {
                                <div id="changetype-button" class="small icon ml-05" title="Change view" onclick="changeView()"></div>
                            }
                        </div>
                    </div>
                    <div class="t-left">
                        <b id="experience-count"></b>
                    </div>
                    <div class="list-container" id="experiences-list-container"></div>
                </div>
            </div>
        </div>
    </div>


    @{await Html.RenderPartialAsync("_Footer"); }
</body>

</html>

www.worldisawesome.fun/Views/Search/People.cshtml
@{
    @using www.worldisawesome.fun;

    if (ViewBag.IsUserSet)
    {
        ViewBag.PictureStream_Preview = Context.Request.Scheme + "://" + Context.Request.Host + Url.Action("GetUserPictureStream", "View", new { pictureId = ViewBag.User.ProfilePhotoFileId, isPreview = true });
    }
    if (ViewBag.IsExperienceSet) {
        ViewBag.FileStream_Preview = Context.Request.Scheme + "://" + Context.Request.Host + Url.Action("GetExperienceMediaStream", "View", new { mediaId = ViewBag.Experience.FileId, isPreview = true });
    }
}

<!DOCTYPE html>
<html lang="en">

<head>
    @{ await Html.RenderPartialAsync("_HeadBase"); }
    <title>Search people | World is Awesome .fun</title>

    <meta name="description" content="Search people in World is Awesome .fun, WiA" />
    <meta name="keywords" content="World is Awesome, World is Awesome .fun, World, Awesome, fun, wia, wia.fun, wia fun, experience, Diary, Travel, Trip, traveller, photo, video, search, people, person, friend">


    <!-- external -->
    <link href="~/lib/font_nunito/Nunito.css" rel="stylesheet">

    <!-- internal -->
    <link rel="stylesheet" href="~/css/style_material.min.css">
    <link rel="stylesheet" href="~/css/style.min.css">

    <script src="~/js/script_vars.min.js" type="text/javascript"></script>
    <script src="~/js/script_apicall.min.js" type="text/javascript"></script>
    <script src="~/js/script_search_people.js" type="text/javascript"></script>
</head>

<body class="loading @(ViewBag.IsUserLogged ? "logged" : "") @(ViewBag.IsMine ? "ismine" : "")">
    @{ await Html.RenderPartialAsync("_Base"); }


    @{ await Html.RenderPartialAsync("_Header"); }


    <div class="article-container" id="people-search-list-popup">

        <div class="article">
            @if (ViewBag.IsUserSet)
            {
                <div class="profile-selected-container">
                    <a href="/View/User?UserId=@ViewBag.User.Id" title="Profile picture" id="userselected-button" class="profile-selected">
                        <img src="@ViewBag.PictureStream_Preview" onerror="this.src='/images/icons/user_avatar_default.svg'" class="icon"
                             alt="profile picture" />
                        <h3 class="text">@ViewBag.User.Nickname</h3>
                    </a>
                </div>
            }
            @if (ViewBag.IsExperienceSet)
            {
                <div class="experience-selected-container">
                    <a href="/View/Experience?ExperienceId=@ViewBag.Experience.Id" title="Experience Media" id="experienceselected-button" class="experience-selected">
                        <img src="@ViewBag.FileStream_Preview" onerror="this.src='/images/icons/media_default.svg'" class="icon"
                             alt="experience media" />
                        <h3 class="text">@ViewBag.Experience.Name</h3>
                    </a>
                </div>
            }

            <div class="article-header d-flex align-items">
                <img src="/images/icons/people_search.svg" class="article-icon" alt="search people" />
                <h2 class="article-title flex-auto">
                    @(ViewBag.IsUserSet ? "Friends" : ViewBag.IsExperienceSet ? "People for ToDo" : "Global People")
                </h2>
            </div>
            <div class="article-body">
                <div class="search-list-container">
                    <div class="input-container search-container" id="people-search-container">
                        <label for="people-search" class="label">Search</label>
                        <input type="search" placeholder="John, Muhammad, Paolo..." id="people-search"
                               class="input" />
                    </div>
                    <div class="t-left">
                        <b id="user-count"></b>
                    </div>
                    <div class="list-container" id="people-list-container"></div>
                </div>
            </div>
        </div>
    </div>


    @{ await Html.RenderPartialAsync("_Footer"); }
</body>

</html>

www.worldisawesome.fun/Views/Search/Places.cshtml
@{
    @using www.worldisawesome.fun;

    if (ViewBag.IsUserSet)
    {
        ViewBag.PictureStream_Preview = Context.Request.Scheme + "://" + Context.Request.Host + Url.Action("GetUserPictureStream", "View", new { pictureId = ViewBag.User.ProfilePhotoFileId, isPreview = true });
    }
}

<!DOCTYPE html>
<html lang="en">

<head>
    @{ await Html.RenderPartialAsync("_HeadBase"); }
    <title>Search places | World is Awesome .fun</title>

    <meta name="description" content="Search places in World is Awesome .fun, WiA" />
    <meta name="keywords"
          content="World is Awesome, World is Awesome .fun, World, Awesome, fun, wia, wia.fun, wia fun, experience, Diary, Travel, Trip, traveller, photo, video, search, places, place, city, country">


    <!-- external -->
    <link href="~/lib/font_nunito/Nunito.css" rel="stylesheet">

    <!-- internal -->
    <link rel="stylesheet" href="~/css/style_material.min.css">
    <link rel="stylesheet" href="~/css/style.min.css">

    <script src="~/js/script_vars.min.js" type="text/javascript"></script>
    <script src="~/js/script_apicall.min.js" type="text/javascript"></script>
    <script src="~/js/script_search_places.js" type="text/javascript"></script>
</head>

<body class="loading @(ViewBag.IsUserLogged ? "logged" : "") @(ViewBag.IsMine ? "ismine" : "")">
    @{ await Html.RenderPartialAsync("_Base"); }


    @{ await Html.RenderPartialAsync("_Header"); }


    <div class="article-container" id="places-search-list-popup">

        <div class="article">
            @if (ViewBag.IsUserSet)
            {
                <div class="profile-selected-container">
                    <a href="/View/User?UserId=@ViewBag.User.Id" title="Profile picture" id="userselected-button" class="profile-selected">
                        <img src="@ViewBag.PictureStream_Preview" onerror="this.src='/images/icons/user_avatar_default.svg'" class="icon"
                             alt="profile picture" />
                        <h3 class="text">@ViewBag.User.Nickname</h3>
                    </a>
                </div>
            }

            <div class="article-header d-flex align-items">
                <img src="/images/icons/place_search.svg" class="article-icon" alt="search places" />
                <h2 class="article-title flex-auto">
                    @(ViewBag.IsUserSet ? "Places" : "Global Places")
                </h2>
            </div>
            <div class="article-body">
                <div class="search-list-container">
                    <div class="input-container search-container" id="places-search-container">
                        <label for="places-search" class="label">Search</label>
                        <div class="d-flex align-items">
                            <input type="search" placeholder="Bogotá, Bogota D.C., Colombia" id="places-search"
                                   class="input" />

                            <div id="morningnight-button" class="small icon ml-05" title="Change daytime" onclick="changeMorningNight()"></div>
                            @if (ViewBag.IsUserSet)
                            {
                                <div id="changetype-button" class="small icon ml-05" title="Change view" onclick="changeView()"></div>
                            }
                        </div>
                    </div>
                    <div class="t-left">
                        <b id="place-count"></b>
                    </div>
                    <div class="list-container" id="places-list-container"></div>
                </div>
            </div>
        </div>
    </div>


    @{ await Html.RenderPartialAsync("_Footer"); }
</body>

</html>